/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author kai
 */
public class ControleLocacao extends javax.swing.JFrame {

    /**
     * Creates new form ControleLocacao
     */
    public ControleLocacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nome");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(27, 14, 27, 14);

        jLabel2.setText("Placa");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(27, 45, 25, 14);

        jLabel3.setText("Ano");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(27, 76, 19, 14);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(58, 11, 109, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(56, 42, 111, 20);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(56, 73, 50, 20);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 120, 400, 10);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(190, 0, 10, 120);

        jLabel4.setText("Locação");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(204, 11, 39, 14);

        jLabel5.setText("Inicio");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(204, 34, 25, 14);

        jLabel6.setText("Entrega");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(204, 65, 38, 14);

        jLabel7.setText("Valor");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(204, 91, 24, 14);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(247, 31, 85, 20);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(246, 62, 86, 20);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(246, 88, 86, 20);

        jLabel8.setText("Itinerario");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(172, 133, 44, 14);

        jLabel9.setText("Origem");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 170, 34, 14);

        jLabel10.setText("Destino");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(200, 170, 36, 14);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(0, 159, 400, 10);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(189, 156, 10, 160);

        jLabel12.setText("Estado");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 210, 33, 14);

        jLabel13.setText("Estado");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(210, 210, 33, 14);

        jLabel14.setText("Cidade");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(10, 260, 33, 14);

        jLabel15.setText("Cidade");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(210, 260, 33, 14);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(10, 230, 100, 20);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(10, 280, 100, 20);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(210, 230, 100, 20);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(210, 280, 100, 20);

        jButton1.setText("Locar");
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 130, 59, 23);

        jButton2.setText("Cancelar");
        getContentPane().add(jButton2);
        jButton2.setBounds(280, 130, 90, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControleLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControleLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControleLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControleLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControleLocacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
